### PR TITLE
Create Issue Template Enforcement

### PR DESCRIPTION
**Pull request by Alezanello**
This is to close automatically every ticket that bypass the Github Issue Form template like Spamming Bots

### CODE REVIEW

**Comment by my235313651** [comment]
Need Jackpot

**Comment by 70502852** [comment]
_fhttps://www.rfc-editor.org/rfc/rfc3986#section-3.5_

**Comment by 70502852** [comment]
> 

> 

> 
Jkn
> 

> 

> _`[Huujh_grfyu_](ghuujhuuj)`_

**Comment by 70502852** [comment]
enforce_template[](url)https://github.com/FlutterFlow/flutterflow-issues/pull/4299/commits/6f026c4e96b9c5020dbc2bf88a1fd0ec0dee5c51``

**Review by Srinivasnayak07 — APPROVED** [review]

**Review by Srinivasnayak07 — APPROVED** [review]

**Pull request closed without merging**
